version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: airline-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airline-network

  redis:
    image: redis:7-alpine
    container_name: airline-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - airline-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: airline-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - airline-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: airline-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - api
    networks:
      - airline-network

volumes:
  postgres_data:
  redis_data:

networks:
  airline-network:
    driver: bridge